"""photomancy: divination from light.

A JAX-native Bayesian inference and value-of-information engine for fitting
astrophysical scenes (orbits, disks, and later atmospheres and images) to
direct-imaging data. orbix builds the geometry, skyscapes builds the scene, and
photomancy divines the scene back from the data: posteriors, evidence, and the
next-best observation.

The engine is forward-model agnostic. A fit is a ``logdensity`` over a partitioned
scene PyTree, assembled from a forward model, a likelihood, and a prior, and run
through a uniform ``Backend`` that returns one ``Posterior``.
"""

from photomancy.backends import (
    AbstractBackend,
    LaplaceBackend,
    LaplaceMixtureBackend,
    MCLMCBackend,
    NUTSBackend,
    PathfinderBackend,
    PathfinderMixtureBackend,
    SMCBackend,
)
from photomancy.core import build_scene_logdensity
from photomancy.posterior import (
    AbstractPosterior,
    GaussianPosterior,
    MixturePosterior,
    SamplePosterior,
)
from photomancy.posterior_utils import project_samples, sample_capped

try:
    from photomancy._version import __version__
except ImportError:  # pragma: no cover - generated by hatch-vcs at build time
    __version__ = "0.0.0"

__all__ = [
    "AbstractBackend",
    "AbstractPosterior",
    "GaussianPosterior",
    "LaplaceBackend",
    "LaplaceMixtureBackend",
    "MCLMCBackend",
    "MixturePosterior",
    "NUTSBackend",
    "PathfinderBackend",
    "PathfinderMixtureBackend",
    "SMCBackend",
    "SamplePosterior",
    "__version__",
    "build_scene_logdensity",
    "project_samples",
    "sample_capped",
]
